### PR TITLE
Add fuzzing

### PR DESCRIPTION
**Pull request by tekknolagi**
This is just the start. There should be more tests.

The test I added makes mutant pass.

### CODE REVIEW

**Comment by ybur-yug** [comment]
So this is where I admit ignorance!

I don't know what this really is doing. Care to explain? :) I could google it but I'm sure (if you dont mind) an explanation from you would probably service my learning better.

**Comment by ybur-yug** [comment]
(It obviously looks like it all works and tests pass locally, but I hesitate to merge before I actually understand what something does heh)

**Comment by ybur-yug** [comment]
PS I really appreciate the interest you've taken this and the contributions @tekknolagi ! I've never had an OSS project that actually got any traction and its awesome to see even if its obviously a bit of a toy tool (though with potential) :)

**Comment by tekknolagi** [comment]
Ah, sorry. Fuzzing is the process of injecting random data into your application. This is not quite that, but perhaps Mutant does that (???). This strips away bits and pieces of your application, checking if it throws errors. So it kind of brute force checks that you have code coverage.

I know the feeling when people have interest in a project and it's a great one! I like Ruby and I like Git so this is perfect ^_^ If only there were a C component now...

Either way, looks great. :+1:

**Comment by ybur-yug** [comment]
A c-component is actually something I am going to toy with tonight. I have a buddy who is coming to visit that is a developer who generally worked with more systems-oriented languages etc and this is on the top of my list :) I really want to get this cross-compatible and usable on a lot of platforms and not just Ruby. If you check the issues someone was cool enough to port the string-store-only version to Python and I've been advising them through the rest of the process.

If you've any resources that would get us in the right direction let me know. We'll probably start hacking on it in an hour or two. Cuz you know, thats how you party on a friday.

**Comment by ybur-yug** [comment]
and knowing that makes sense and I shall merge! :) lgtm

**Comment by ybur-yug** [comment]
PS it looks like Mutant does that via singleton instances of each class so it appears that thought is correct :)

**Comment by tekknolagi** [comment]
I dunno — do you mean for Python or C? Keep me posted with the C stuff! It's what I am best at. :)

**Comment by ybur-yug** [comment]
Tonight's topic is a C-extension! Not Python. That was just someone who wanted a quick port. But yeah the main idea is to get a C package set up so that it can be trivially bound to whatever language that is C-Contiguous. Obviously there are many more subtleties than that but we will at least be experimenting with it. If you'd like to add me on gchat and will be available tonight we'll be starting around 8pm EST (5pm your time) and I'd gladly have a chat about the best method to getting this up and running! bobbygrayson[at]gmail[dot]com

**Comment by tekknolagi** [comment]
How'd it go?

2015-06-26 15:33 GMT-07:00 yburyug <notifications@github.com>:

**Comment by ybur-yug** [comment]
Heh somewhere between getting distracted and shiny object syndrome. Started toying with Rust over C and wrapping the needed C portions in that. Got nothing actually useable in any capacity, though. But it could be reasonable to do.

**Pull request merged**
